### ISSUE TITLE
Ongoing issues

### ISSUE THREAD

**Issue by awesomebing1** [Seriell/Serie-Bot#19]
The following is an ongoing issue tracker of minor issues with Serie-Bot.

- '~~`avatar` shows the user's own avatar, regardless of mentioning for another user~~

**Comment by awesomebing1** [comment]
It's probably a better idea to open issues individually instead of collectively. Closing.

**Comment by Seriell** [comment]
Agreed, issues should have their own pages for discussing the individual issue etc
