### ISSUE TITLE
Prettify Channel Mentions

### ISSUE THREAD

**Issue by Seriell** [Seriell/Serie-Bot#5]
At the moment when a channel is mentioned and logged, it uses the format <#LONG-ID>
For example:

```
(AACAHw==) [10/21/16 15:10] Seriel's Corner/#bot-stuff <Seriel#0757> <#238970230175563776> <#228625269101953035>
```

This looks untidy and isn't clear which channel is being mentioned, ideally you would want some kind of prettified channel mentions similar to how member mentions are displayed as `@User#1234` instead of `<@LONG-ID>`

**Comment by larsenv** [comment]
You need these ingredients:

- A loaf of bread
- Butter
- Ice Cream
- Chocolate Chips

Steps

1. Put the butter and bread in a mixing bowl. Mix them good together.
2. Bake the bread mixture at 450°F.
3. Put that into a tray.
4. Put the ice cream and chocolate chips in another mixing bowl. Mix them good together.
5. Put them in a refrigerator.
6. Take the ice cream mixture and bread mixture then mix them together.
7. Put them in a refrigerator.
8. Enjoy your Prettify Channel Mentions.

**Comment by Seriell** [comment]
Added in https://github.com/Seriell/Serie-Bot/commit/069f9283a3be04d3d94b9bd12db2a99b43f6ccca
